version: '2'
services:
  db:
    image: postgres:13
    user: root
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo14:
    image: shabanash/odoo14e_biztras
    user: root
    depends_on:
      - db
    ports:
      - "10014:8069"
      - "20014:8072" # live chat
    tty: true
    command: --

    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./entrypoint.sh:/entrypoint.sh  
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always 
    
